name: Create Release ZIP

on:
  release:
    types: [published]

jobs:
  build-and-zip:
    runs-on: ubuntu-latest

    steps:
      # Vérifier le dépôt
      - name: Checkout repository
        uses: actions/checkout@v3

      # Debug : Afficher les variables pour vérifier le GITHUB_TOKEN
      - name: Debug GITHUB_TOKEN
        run: |
          echo "GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}"
          echo "Release upload URL: ${{ github.event.release.upload_url }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Installer l'outil zip
      - name: Install zip
        run: sudo apt-get install -y zip

      # Créer le fichier ZIP
      - name: Create ZIP excluding setup.php
        run: |
          mkdir -p dist
          VERSION=${{ github.event.release.tag_name }}
          zip -r ./dist/release-${VERSION}.zip public -x "public/setup.php"

      # Joindre le fichier ZIP à la release
      - name: Upload ZIP to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./dist/release-${{ github.event.release.tag_name }}.zip
          asset_name: release-${{ github.event.release.tag_name }}.zip
          asset_content_type: application/zip
