name: Create Release ZIP

on:
  release:
    types: [published] # L'action se déclenche uniquement lors de la publication d'une release

permissions:
  contents: write
  releases: write

jobs:
  build-and-zip:
    runs-on: ubuntu-latest

    steps:
      # Vérifier le dépôt
      - name: Checkout repository
        uses: actions/checkout@v3

      # Installer l'outil zip
      - name: Install zip
        run: sudo apt-get install -y zip

      # Créer le fichier ZIP
      - name: Create ZIP excluding setup.php
        run: |
          mkdir -p dist
          VERSION=${{ github.event.release.tag_name }} # Utilise le numéro de version depuis la release
          zip -r ./dist/release-${VERSION}.zip public -x "public/setup.php"

      # Joindre le fichier ZIP à la release
      - name: Upload ZIP to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./dist/release-${{ github.event.release.tag_name }}.zip
          asset_name: release-${{ github.event.release.tag_name }}.zip
          asset_content_type: application/zip
